spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/locadrive
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # Hibernate will update the tables without dropping them or create them if they do not exist
    show-sql: true # prints the sql commands in the console
